name: Validate Pull Request

on:
  pull_request:

jobs:
  validate-pull-request:
    name : Validate Pull Request
    uses: Lombiq/GitHub-Actions/.github/workflows/validate-submodule-pull-request.yml@dev
