name: Validate Pull Request

on:
  pull_request_target:

jobs:
  validate-pull-request:
    name : Validate Pull Request
    uses: Lombiq/GitHub-Actions/.github/workflows/validate-submodule-pull-request.yml@dev
    with:
      repository: Lombiq/Hastlayer-SDK
